runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.65
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
network: 
  instance_tag: allow-health-check
  name: default
  subnetwork_name: default
